/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef GAME_CONTROLLER_FRAMEWORK_KEY_TO_TOUCH_MANAGER_H
#define GAME_CONTROLLER_FRAMEWORK_KEY_TO_TOUCH_MANAGER_H

#include <singleton.h>
#include <unordered_map>
#include "key_to_touch_handler.h"
#include "gamecontroller_client_model.h"
#include "gamecontroller_keymapping_model.h"
#include "ffrt.h"

namespace OHOS {
namespace GameController {
class KeyToTouchManager : public DelayedSingleton<KeyToTouchManager> {
DECLARE_DELAYED_SINGLETON(KeyToTouchManager)

public:
    void SetSupportKeyMapping(bool isSupportKeyMapping, const std::unordered_set<int32_t> &deviceTypeSet);

    bool DispatchKeyEvent(const std::shared_ptr<MMI::KeyEvent> &keyEvent);

    bool DispatchPointerEvent(const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    void UpdateTemplateConfig(const DeviceTypeEnum &deviceType, const std::string &bundleName,
                              const std::vector<KeyToTouchMappingInfo> &mappingInfos);

    void UpdateWindowInfo(const WindowInfoEntity &windowInfoEntity);

    void EnableKeyMapping(const std::string &bundleName, bool isEnable);

    void UpdateByDeviceStatusChanged(const DeviceInfo &deviceInfo);

    void SetCurrentBundleName(const std::string &bundleName, bool isEnable, bool isPluginMode);

    /**
     * Clear keymapping of the current game. It's only called by plugin-mode
     */
    void ClearGameKeyMapping();

    /**
     * Periodically check whether it is necessary to send a pointer move message
     */
    void CheckPointerSendInterval();

    /**
     * when focus status is changed, reset context
     * @param bundleName bundleName
     * @param isFocus isFocus
     */
    void UpdateFocusStatus(const std::string &bundleName, bool isFocus);

    /**
     * Inject a synthetic key event generated by trigger axis crossing.
     * Called by TriggerToTouchHandler to route through normal key dispatch.
     */
    void InjectGamepadTriggerKey(std::shared_ptr<InputToTouchContext> &context,
        int32_t keyCode, int32_t keyAction, int64_t actionTime);

    /**
     * Reset axis handler states when skill ends to prevent
     * unwanted observation/walking trigger on the next axis event.
     */
    void ResetAxisHandlerStates();

    void CancelStickTimers();

    /**
     * Update cached stick axis values for dead-zone detection.
     * Called from HandleGamePadAxisEvent for every axis event.
     */
    void UpdateStickAxisCache(const std::shared_ptr<MMI::PointerEvent> &pointerEvent, int32_t joystick);

    bool IsStickInDeadZone(int32_t joystick) const;

private:
    bool IsDispatchToPluginMode(const std::shared_ptr<MMI::KeyEvent> &keyEvent);

    bool IsCanEnableKeyMapping();

    bool DeviceIsSupportKeyMapping(DeviceTypeEnum deviceTypeEnum);
    void HandleKeyEvent(const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                        const DeviceTypeEnum &deviceType,
                        const DeviceInfo &deviceInfo);

    void HandlePointerEvent(const std::shared_ptr<MMI::PointerEvent> &pointerEvent, const DeviceTypeEnum &deviceType);

    void HandleGamePadAxisEvent(const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    bool IsGamePadAxisEvent(const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    void DetectGamePadStickEvent(const std::shared_ptr<MMI::PointerEvent> &pointerEvent,
                                 bool &hasLeft, bool &hasRight) const;
    void RouteGamePadStick(const std::shared_ptr<MMI::PointerEvent> &pointerEvent,
                           int32_t joystick);

    void RouteGamePadTrigger(const std::shared_ptr<MMI::PointerEvent> &pointerEvent,
                              int32_t targetJoystick);
    /**
     * Get mapping info
     * @param context context
     * @param keyEvent keyEvent
     * @param deviceInfo deviceInfo
     * @param keyToTouchMappingInfo out param
     * @return true means get mapping info success
     */
    bool GetMappingInfoByKeyCode(const std::shared_ptr<InputToTouchContext> &context,
                                 const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                                 const DeviceInfo &deviceInfo,
                                 KeyToTouchMappingInfo &keyToTouchMappingInfo);

    bool GetMappingInfoByKeyCodeWhenKeyDown(const std::shared_ptr<InputToTouchContext> &context,
                                            const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                                            const DeviceInfo &deviceInfo,
                                            KeyToTouchMappingInfo &keyToTouchMappingInfo);

    bool GetMappingInfoByKeyCodeWhenKeyUp(const std::shared_ptr<InputToTouchContext> &context,
                                          const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                                          KeyToTouchMappingInfo &keyToTouchMappingInfo);

    bool GetMappingInfoByKeyCodeFromCombinationKey(const std::shared_ptr<InputToTouchContext> &context,
                                                   const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                                                   const DeviceInfo &deviceInfo,
                                                   KeyToTouchMappingInfo &keyToTouchMappingInfo);

    void HandleTemplateConfig(const DeviceTypeEnum &deviceType,
                              const std::vector<KeyToTouchMappingInfo> &mappingInfos);

    void HandleWindowInfo(const WindowInfoEntity &windowInfoEntity);

    void UpdateContextWindowInfo(const std::shared_ptr<InputToTouchContext> &context);

    void InitGcKeyboardContext(const std::vector<KeyToTouchMappingInfo> &mappingInfos);

    void InitHoverTouchPadContext(const std::vector<KeyToTouchMappingInfo> &mappingInfos);

    void InitGpInputToTouchContext(const std::vector<KeyToTouchMappingInfo> &mappingInfos);

    void CancelGamePadHandlerTimers();
    void InjectTriggerBridgeMappings();

    void ReleaseContext(const std::shared_ptr<InputToTouchContext> &inputToTouchContext);

    void ResetMonitor();

    void ResetAllMonitorKeysAndMouseMonitor(const std::shared_ptr<InputToTouchContext> &context);

    void AddToMonitorKeys(const DeviceTypeEnum &deviceType,
                          const std::unordered_map<int32_t, KeyToTouchMappingInfo> &keyMap);

    void AddToMonitorKeys(const DeviceTypeEnum &deviceType,
                          const int32_t &keyCode);

    bool IsHandleMouseMove(std::shared_ptr<InputToTouchContext> &context,
                           const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    bool IsHandleMouseRightButtonEvent(std::shared_ptr<InputToTouchContext> &context,
                                       const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    bool IsHandleMouseLeftButtonEvent(std::shared_ptr<InputToTouchContext> &context,
                                      const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    void ExecuteHandle(std::shared_ptr<InputToTouchContext> &context,
                       const KeyToTouchMappingInfo &mappingInfo,
                       const std::shared_ptr<MMI::KeyEvent> &keyEvent,
                       const DeviceInfo &deviceInfo);

    void ExecuteHandle(std::shared_ptr<InputToTouchContext> &context,
                       const KeyToTouchMappingInfo &mappingInfo,
                       const std::shared_ptr<MMI::PointerEvent> &pointerEvent);

    void HandleEnableKeyMapping(bool isEnable);

    void ResetContext(std::shared_ptr<InputToTouchContext> &context);

private:
    bool isSupportKeyMapping_{false};
    std::unordered_set<int32_t> supportDeviceTypeSet_;
    ffrt::mutex checkMutex_;
    std::unique_ptr<ffrt::queue> handleQueue_{nullptr};
    ffrt::task_handle curTaskHandler_{nullptr};
    std::unordered_map<MappingTypeEnum, std::shared_ptr<BaseKeyToTouchHandler>> mappingHandler_;
    std::shared_ptr<InputToTouchContext> gcKeyboardContext_{nullptr};
    std::shared_ptr<InputToTouchContext> hoverTouchPadContext_{nullptr};
    std::shared_ptr<InputToTouchContext> gamePadContext_{nullptr};
    std::unordered_map<int32_t, std::unordered_set<DeviceTypeEnum>> allMonitorKeys_;
    std::unordered_map<int32_t, KeyToTouchMappingInfo> triggerMappings_;
    bool isMonitorMouse_{false};
    WindowInfoEntity windowInfoEntity_;
    bool isEnableKeyMapping_{true};std::string bundleName_;
    bool isPluginMode_{false};

    /**
     * Per-joystick suppression: after a skill ends with the stick pushed,
     * suppress all camera/view routing until the stick returns to center.
     * Indices: [0] = left stick, [1] = right stick.
     */
    bool stickPushedDuringSkill_[2] = {false, false};
    bool suppressStickCamera_[2] = {false, false};

    /** Cached axis values for dead-zone detection (updated on every axis event). */
    double cachedStickAxisX_[2] = {0.0, 0.0};
    double cachedStickAxisY_[2] = {0.0, 0.0};

    /** Consecutive dead-zone frame counter for suppression clear. */
    int32_t suppressDeadCounter_[2] = {0, 0};

    static constexpr double STICK_CENTER_DEAD_ZONE = 0.05;
    static constexpr int32_t STICK_CENTER_CONFIRM_FRAMES = 3;
};
}
}

#endif //GAME_CONTROLLER_FRAMEWORK_KEY_TO_TOUCH_MANAGER_H
